### PR TITLE
Flexible platform subdir

### PR DESCRIPTION
**Pull request by Tobias-Fischer**
Progress toward fixing #16

### CODE REVIEW

**Comment by Tobias-Fischer** [comment]
It still fails though:
```
Traceback (most recent call last):
  File "/Users/tobias/opt/anaconda3/bin/boa", line 33, in <module>
    sys.exit(load_entry_point('boa', 'console_scripts', 'boa')())
  File "/Users/tobias/robot/boa/boa/cli/boa.py", line 813, in main
    solver.replace_channels()
  File "/Users/tobias/robot/boa/boa/cli/mambabuild.py", line 144, in replace_channels
    self.local_index = get_index(("local",), platform=self.platform, prepend=False)
  File "/Users/tobias/robot/boa/boa/cli/mambabuild.py", line 110, in get_index
    is_downloaded = dlist.download(True)
RuntimeError: Download error (37) Couldn't read a file:// file [file:///Users/tobias/opt/anaconda3/conda-bld/noarch/repodata.json]
```
Any hints @wolfv?

**Comment by wolfv** [comment]
I think we need to call `update_index` or some function like this _before_ we attempt to load the (local) repo.
You can do it manually by navigating to `/Users/tobias/opt/anaconda3/conda-bld` and run `conda index`

And programmatically there is something like an `update_index` function in conda build.

**Comment by Tobias-Fischer** [comment]
After running `conda index`, I still run into the original error:

```
Traceback (most recent call last):
  File "/Users/tobias/opt/anaconda3/bin/boa", line 33, in <module>
    sys.exit(load_entry_point('boa', 'console_scripts', 'boa')())
  File "/Users/tobias/robot/boa/boa/cli/boa.py", line 813, in main
    solver.replace_channels()
  File "/Users/tobias/robot/boa/boa/cli/mambabuild.py", line 151, in replace_channels
    cp = subdir.cache_path()
RuntimeError: Cache not loaded!
```

**Comment by wolfv** [comment]
can you check that the subdir exists and the repodata.json file is there?

`/Users/tobias/opt/anaconda3/conda-bld/noarch/repodata.json`
and
`/Users/tobias/opt/anaconda3/conda-bld/osx-64/repodata.json`

**Comment by Tobias-Fischer** [comment]
Ha - thanks, I needed to create the `osx-64` folder manually and then run `conda index`. It seems to work now! I suggest to merge this PR and deal with `update_index` separately - I'll leave this part up to you if that's okay with you.

**Comment by wolfv** [comment]
sure

**Pull request merged**
